# 最佳组合, 可选组合: T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17
tx_str = "T2,T4,T7"
# 奇偶, 可能的奇偶: "07","16","25","34","43","52","61","70",多个可能用英文","隔开
oe_str = "34,43"
# 和值范围最小18,最大188
hz_min = 98
hz_max = 108

# 必须包含的号码
# 前区必须包含的号码,多个号码用英文","隔开
front_include_hm_str = "08"
# 后区必须包含的号码,多个号码用英文","隔开
back_include_hm_str = "08,11,12"

# 必须排除的号码
# 前区必须排除的号码,范围为01到35,多个号码用英文","隔开
front_exclude_hm_str = "03,18,19"

# 后区必须排除的号码,范围为01到12,多个号码用英文","隔开
back_exclude_hm_str = "01"

# 前区号码中前中后的号码个数, 前(01~17);中(18);后(19~35), 例如: "203"表示在0~17中选2个号码,在19~35中选择3个号码, 多个可能用英文","隔开
qzh_str = "203,311,302"

# 新增4重号数必须大于等于的数值
ch4_must_GET_count = 20