CREATE TABLE `dlts`
(
    `id`                 bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
    `draw_num`           varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '期号',
    `draw_time`          varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '开奖时间',
    `equipment_count`    int NULL DEFAULT 0 COMMENT '开奖设备号',
    `draw_pdf_url`       varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT 'pdf地址',
    `unsort_draw_result` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '',
    `f1`                 varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '前区第一个号码',
    `f2`                 varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '前区第二个号码',
    `f3`                 varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '前区第三个号码',
    `f4`                 varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '前区第四个号码',
    `f5`                 varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '前区第五个号码',
    `b1`                 varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '后区第一个号码',
    `b2`                 varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '后区第二个号码',
    `pool_balance`       decimal(15, 2) NULL DEFAULT 0.00 COMMENT '奖池奖金(元)',
    `total_sale_amount`  decimal(15, 2) NULL DEFAULT 0.00 COMMENT '当期总销售额(元)',
    `stake_count_101`    int NULL DEFAULT 0 COMMENT '一等奖注数',
    `stake_count_102`    int NULL DEFAULT 0 COMMENT '一等奖基本派奖注数',
    `stake_count_201`    int NULL DEFAULT 0 COMMENT '一等奖追加注数',
    `stake_count_202`    int NULL DEFAULT 0 COMMENT '一等奖追加派奖注数',
    `stake_count_301`    int NULL DEFAULT 0 COMMENT '二等奖注数',
    `stake_count_302`    int NULL DEFAULT 0 COMMENT '二等奖基本派奖注数',
    `stake_count_401`    int NULL DEFAULT 0 COMMENT '二等奖追加注数',
    `stake_count_402`    int NULL DEFAULT 0 COMMENT '二等奖追加派奖注数',
    `stake_count_501`    int NULL DEFAULT 0 COMMENT '三等奖注数',
    `stake_count_601`    int NULL DEFAULT 0 COMMENT '四等奖注数',
    `stake_count_701`    int NULL DEFAULT 0 COMMENT '五等奖注数',
    `stake_count_801`    int NULL DEFAULT 0 COMMENT '六等奖注数',
    `stake_count_901`    int NULL DEFAULT 0 COMMENT '七等奖注数',
    `stake_count_1001`   int NULL DEFAULT 0 COMMENT '八等奖注数',
    `stake_count_1101`   int NULL DEFAULT 0 COMMENT '九等奖注数',
    `stake_count_60`     int NULL DEFAULT 0 COMMENT '三等奖追加注数',
    `stake_count_80`     int NULL DEFAULT 0 COMMENT '四等奖追加注数',
    `stake_count_100`    int NULL DEFAULT 0 COMMENT '五等奖追加注数',
    `stake_amount_101`   int NULL DEFAULT 0 COMMENT '一等奖奖金(元)',
    `stake_amount_102`   int NULL DEFAULT 0 COMMENT '一等奖基本派奖奖金(元)',
    `stake_amount_201`   int NULL DEFAULT 0 COMMENT '一等奖追加奖金(元)',
    `stake_amount_202`   int NULL DEFAULT 0 COMMENT '一等奖追加派奖奖金(元)',
    `stake_amount_301`   int NULL DEFAULT 0 COMMENT '二等奖奖金(元)',
    `stake_amount_302`   int NULL DEFAULT 0 COMMENT '二等奖基本派奖奖金(元)',
    `stake_amount_401`   int NULL DEFAULT 0 COMMENT '二等奖追加奖金(元)',
    `stake_amount_402`   int NULL DEFAULT 0 COMMENT '二等奖追加派奖奖金(元)',
    `stake_amount_501`   int NULL DEFAULT 0 COMMENT '三等奖奖金(元)',
    `stake_amount_601`   int NULL DEFAULT 0 COMMENT '四等奖奖金(元)',
    `stake_amount_701`   int NULL DEFAULT 0 COMMENT '五等奖奖金(元)',
    `stake_amount_801`   int NULL DEFAULT 0 COMMENT '六等奖奖金(元)',
    `stake_amount_901`   int NULL DEFAULT 0 COMMENT '七等奖奖金(元)',
    `stake_amount_1001`  int NULL DEFAULT 0 COMMENT '八等奖奖金(元)',
    `stake_amount_1101`  int NULL DEFAULT 0 COMMENT '九等奖奖金(元)',
    `stake_amount_60`    int NULL DEFAULT 0 COMMENT '三等奖追加奖金(元)',
    `stake_amount_80`    int NULL DEFAULT 0 COMMENT '四等奖追加奖金(元)',
    `stake_amount_100`   int NULL DEFAULT 0 COMMENT '五等奖追加奖金(元)',
    `created_at`         datetime NULL DEFAULT NULL COMMENT '创建时间',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;